# Model images
FROM lab-registry-quay-openshift-operators.apps.ocp.lab.home/watson-libs/watson-tts-generic-models:1.0.0 AS catalog
# Add additional models here
FROM lab-registry-quay-openshift-operators.apps.ocp.lab.home/watson-libs/watson-tts-en-us-michaelv3voice:1.0.0 AS en-us-voice
FROM lab-registry-quay-openshift-operators.apps.ocp.lab.home/watson-libs/watson-tts-en-gb-jamesv3voice:1.0.0 AS en-gb-voice

# Base image for the runtime
FROM lab-registry-quay-openshift-operators.apps.ocp.lab.home/watson-libs/watson-tts-runtime:1.0.0 AS runtime

# Environment variable used for directory where configurations are mounted
ENV CONFIG_DIR=/opt/ibm/chuck.x86_64/var

# Copy in the catalog and runtime configurations
COPY --chown=watson:0 --from=catalog catalog.json ${CONFIG_DIR}/catalog.json
# COPY --chown=watson:0 ./chuck_var/* ${CONFIG_DIR}/
COPY --chown=watson:0 ./${LOCAL_DIR}/* ${CONFIG_DIR}/

# Intermediate image to populate the model cache
FROM runtime as model_cache

# Copy model archives from model images
RUN sudo mkdir -p /models/pool2
# For each additional models, copy the line below with the model image
COPY --chown=watson:0 --from=en-us-voice model/* /models/pool2/
COPY --chown=watson:0 --from=en-gb-voice model/* /models/pool2/

# Run script to initialize the model cache from the model archives
COPY ./prepareModels.sh .

RUN ./prepareModels.sh

# Final runtime image with models baked in
FROM runtime as release

COPY --from=model_cache ${CONFIG_DIR}/cache/ ${CONFIG_DIR}/cache/